[package]
name = "urlquote"
version = "0.4.0"
authors = ["Blue Yonder <oss@blue-yonder.com>"]
publish = false
edition = "2018"

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
percent-encoding = "2.1.0"
